### PR TITLE
Bring back changes to services.py from 0.3.1 just fix import logic

### PR DESCRIPTION
**Pull request by wbarnha**
Let's properly test things with Faust from hereon to make sure there aren't issues like this again in the future.

The big mistake we made was changing the imports of
```python
from .utils.contexts import AsyncExitStack, ExitStack
from .utils.locks import Event
```
to
```
from asyncio.locks import Event
from contextlib import AsyncExitStack, ExitStack
```
Hopefully we won't encounter #33 again.

### CODE REVIEW

**Comment by wbarnha** [comment]
Just tested it with Faust v0.10.0, it's safe for merging.

**Comment by lqhuang** [comment]
It's fine for me to temporarily rebase back to old codes to fix bugs, so I agree to merge it for now. But, IMHO, I still think we should adapt with std implementation, only except stdlib really do not provide the extra function we need.

How do you think about it?

**Review by lqhuang — APPROVED** [review]
LGTM, seems nothing changed

**Comment by lqhuang** [comment]
Feel free to @me from `faust`, I will provide my opinions as I could. Thanks to @wbarnha, you have made a lot of work to let community become active 👍

**Pull request merged**
