### PR TITLE
Style: go to pyproject.toml

### PR DESCRIPTION
**Pull request by manawasp**
Hello !

This PR is still in draft state.

While migrating to pyproject.toml I got issue with Sphinx and I was wondering if you want to keep Sphinx or If I could migrate to mkdocs with material theme ?

### CODE REVIEW

**Comment by wbarnha** [comment]
Thanks for the PR! I'm not a fan of how things are currently set up with Sphinx, so if switching to mkdocs makes things more readable, then sure! Let me look around at the changes to see if this is a good switch.

**Comment by manawasp** [comment]
Small update here @wbarnha :

Screenshot of the documentation:

**Main page**
screen

**References**
screen-refs

1. _I think the main content can be reworked in a later PR_
2. The main documentation color can be changed as you please, [here are default](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color) but we can set any hexa color.


_You can serve documentation locally by running in new venv `pip install -r requirements.txt` then `make serve-docs` (or just `mkdocs serve`)._


About this PR I still have:

- [ ] Validate command to build package
- [ ] Handle versioning correctly
- [ ] I don't know if Makefile is usefull or can be dropped I feel other python OSS prefer `scripts/*` 
- [ ] Pass the pipeline :heavy_check_mark:

**Review by wbarnha — CHANGES_REQUESTED** [review]
I definitely like this documentation style much more. Once the CI/CD builds pass again, I support the changes! Obviously I'll run things locally to see how they look to get a better glimpse. Sorry for the late response.

**Comment by manawasp** [comment]
No problem ! The work on the documentation is done. I have fixed the pipeline except on related `pypy` locally I can't reproduce the issue do you have an idea of the current issue ?

**Comment by wbarnha** [comment]
> No problem ! The work on the documentation is done. I have fixed the pipeline except on related `pypy` locally I can't reproduce the issue do you have an idea of the current issue ? @wbarnha

PyPy tends to be a bit quirky. Let's add a test for PyPy 3.9 again as well, out of curiosity.

**Comment by wbarnha** [comment]
Oh, 3.9 failed as well.

**Comment by wbarnha** [comment]
I'll need a bit to revisit this, I'm in the middle of some things at the moment.

**Comment by manawasp** [comment]
> I'll need a bit to revisit this, I'm in the middle of some things at the moment.

:ok_hand: in other case I will try to reproduce it this weekend locally via Docker maybe I will catch it :D

**Comment by manawasp** [comment]
Some news !

I started to backport changes little by little starting again from master and the pipeline is passing... So I will do it carely to catch to thing generating this issue.

https://github.com/manawasp/mode/pull/2/files

(And finally I will update changes here)

**Review by wbarnha — COMMENTED** [review]
It's hard to decipher what could be responsible for breaking PyPy tests. It seems to be pointing to something related to the setup.

**Comment by manawasp** [comment]
Finally a green pipeline @wbarnha !! Look like related to this option ` --cov=mode`.

I will rebase all commits to make something cleaner

**Review by wbarnha — APPROVED** [review]
Thanks for your hard work, LGTM!

**Comment by manawasp** [comment]
> Thanks for your hard work, LGTM!

Your welcome didn't have time to rewrite commit but that's fine! We should try to generate the new documentation but to do that we need to publish a new tag and a release, maybe a pre-release could work ? :thinking:

**Comment by manawasp** [comment]
@wbarnha little ping just to be sure you if you caught my previous message :D

**Comment by wbarnha** [comment]
```python
Warning: Trusted Publishers allows publishing packages to PyPI from automated environments like GitHub Actions without needing to use username/password combinations or API tokens to authenticate with PyPI. Read more: https://docs.pypi.org/trusted-publishers
Checking dist/mode_streaming-0.3.5-py2.py3-none-any.whl: PASSED
Uploading distributions to https://upload.pypi.org/legacy/
Uploading mode_streaming-0.3.5-py2.py3-none-any.whl
25l
  0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/115.1 kB • --:-- • ?
  0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/115.1 kB • --:-- • ?
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.1/115.1 kB • 00:00 • 3.0 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.1/115.1 kB • 00:00 • 3.0 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.1/115.1 kB • 00:00 • 3.0 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.1/115.1 kB • 00:00 • 3.0 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.1/115.1 kB • 00:00 • 3.0 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.1/115.1 kB • 00:00 • 3.0 MB/s
25hWARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         File already exists. See https://pypi.org/help/#file-name-reuse for    
         more information.                                                      
```
Welp. Looks like something got broken. Did setuptools-scm get removed inadvertently?

**Comment by wbarnha** [comment]
This is weird, I don't recall my Github Pages deployment workflow being this janky. Apparently last deployment was in 2022. I don't remember what got altered...

**Comment by wbarnha** [comment]
There we go, it's on https://faust-streaming.github.io/mode/ now! I forgot about the workflow I configured for deploying pages. It's been a while and it's such a small, easy detail to overlook.

**Comment by wbarnha** [comment]
These pages are so nice. Thank you so much for your work, @manawasp!

**Pull request merged**
