### PR TITLE
Fix passing coroutine objects to `wait()`

### LINKED ISSUE #19: mode not ready for 3.11
In the spirit of https://github.com/faust-streaming/mode/issues/9

The issues were highlighted in the above issue but mitigated not fixed. The error below is because of [asyncio.wait](https://docs.python.org/3/library/asyncio-task.html#asyncio.wait), which has had passing coroutines deprecated since 3.8 and now removed in 3.11.

As an aside, it looks like `aiokafka` also has plenty of these and hasn't released in over a year (with a few blockers apparently), so it looks like a ton of work to get things working with 3.11.

## Checklist

- [ x] I have included information about relevant versions
- [x ] I have verified that the issue persists when using the `master` branch of Mode.

## Steps to reproduce

Try to run with python 3.11

## Expected behavior

Run as with <3.11

## Actual behavior

Error

## Full traceback

```pytb
faustworker_1  |     [2022-10-25 09:01:53,673] [10] [INFO] [^---AIOKafkaConsumerThread]: Stopping... 
faustworker_1  |       ^^^^^^^^^^^^^^^                                                                                              
faustworker_1  |   File "/usr/local/lib/python3.11/site-packages/mode/threads.py", line 253, in _serve
faustworker_1  |     await self.wait_until_stopped()                                                                                
faustworker_1  |   File "/usr/local/lib/python3.11/site-packages/mode/services.py", line 1005, in wait_until_stopped
faustworker_1  |     await self.wait()                                                                                              
faustworker_1  |   File "/usr/local/lib/python3.11/site-packages/mode/services.py", line 722, in wait
faustworker_1  |     await self._wait_stopped(timeout=timeout)                                                                      
faustworker_1  |   File "/usr/local/lib/python3.11/site-packages/mode/services.py", line 794, in _wait_stopped
faustworker_1  |     done, pending = await asyncio.wait(                                                                            
faustworker_1  |                     ^^^^^^^^^^^^^^^^^^^                                                                            
faustworker_1  |   File "/usr/local/lib/python3.11/asyncio/tasks.py", line 415, in wait
faustworker_1  |     raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
faustworker_1  | TypeError: Passing coroutines is forbidden, use tasks explicitly.
```

# Versions

* Python version 3.11
* Mode version 0.2.1
* Operating system Linux (python-3.11.0-slim docker image)

### PR DESCRIPTION
**Pull request by lqhuang**
*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.fauststream.com/en/master/contributing.html).

## Description

Due to break change introduced in Python 3.11, [`wait()`](https://docs.python.org/3/library/asyncio-task.html#asyncio.wait) only accept scheduled tasks.

> Changed in version 3.11: Passing coroutine objects to `wait()` directly is forbidden.

In [services.py line 794](https://github.com/faust-streaming/mode/blob/d87d88362034b8663613c1502858234de7a5de93/mode/services.py#L794) of current master, two coroutines are passed into `wait()` function. So the program exits.

```
stopped = self._stopped.wait()
crashed = self._crashed.wait()
done, pending = await asyncio.wait(
    [stopped, crashed],
    return_when=asyncio.FIRST_COMPLETED,
    timeout=timeout,
)
```

This PR fixes #19.

This patch is enough to let `mode` successfully run under Python 3.11 except passing all test cases. Current tests of `mode` rely on its self defined `AsyncMock` which is already not working under py3.11, 
so there are still a lot of hard work to rewrite test cases to make everything looks good.

### CODE REVIEW

**Comment by wbarnha** [comment]
> This patch is enough to let mode successfully run under Python 3.11 except passing all test cases. Current tests of mode relies on its self defined AsyncMock already not working under py3.11,

Very interesting, I'll test this branch with faust-streaming before merging, assuming all test cases above pass for all other versions of Python.

**Comment by lqhuang** [comment]
@wbarnha Maybe we should stop actions? Something blocked, it already runs 3hrs more. I'm afraid to consume all free time.

**Comment by lqhuang** [comment]
I see. I removed `from asyncio import coroutine`, so tests for all past Python failed, too.

**Comment by lqhuang** [comment]
@wbarnha Hey, you could review now, I have fixed all tests with new standard library modules.

**Comment by lqhuang** [comment]
@wbarnha You can review it now. I have fixed all tests. It should fit all versions after Python 3.8

**Comment by wbarnha** [comment]
That's incredible! Fantastic work @lqhuang! I'll see if I can add compatibility for 3.7+3.8, or we could just drop support for those versions.

**Comment by lqhuang** [comment]
Actually, the incompatibility for both Py3.7 and Py3.8 happens in test codebase. Py3.8 is caused by the nested `with` syntax.

**Review by wbarnha — APPROVED** [review]
Thank you so much! LGTM!

**Comment by lqhuang** [comment]
Also, thank you for your efforts in review work!

**Comment by wbarnha** [comment]
Regarding commit https://github.com/faust-streaming/mode/pull/24/commits/14ca9814d1eda3740be365c339414d7156edb882, I think we need to bring the mocks back because they had specific logic that was hardcoded for faust-streaming unittests...

**Comment by lqhuang** [comment]
I definitely understand. Sure, you could bring them back, but the key problem is this module also will make `faust-streaming` unable to run under Python 3.11. I said it would be a hard work to upgrade test cases for both `mode` and `faust`.

**Comment by wbarnha** [comment]
Yeah, I'm starting to remember why you removed the mocks. Upgrading the test cases for Faust will take a while.

**Comment by lqhuang** [comment]
I also read codes from `faust`, through I does't use it yet, otherwise I could help to maintain it either. One good thing is you could start from simply replace codes in special pattern. Basically, updating `.coro.assert_called_once[_with]()` with `.assert_awaited_once[_with]()` works in most cases. Hope my commits in this PR will give you a hand.

**Comment by wbarnha** [comment]
> Basically, updating `.coro.assert_called_once[_with]()` with `.assert_awaited_once[_with]()`

I've observed the same thing! I'll keep trying to go through the unit tests. I've made some progress but there are some quirks I still need to clear up.

**Pull request merged**
