### PR TITLE
style(black): apply new format style from black

### PR DESCRIPTION
**Pull request by manawasp**
Fix CI issue seen in the PR https://github.com/faust-streaming/mode/pull/48 

(I preferred opened another PR to fix this)

### CODE REVIEW

**Comment by manawasp** [comment]
Thanks for the CI noticed some issue :

> FAILED t/unit/test_services.py::test_Service::test_wait_first__propagates_exceptions - RuntimeError: Event loop is closed


I will take a look later, I believe there is a not pin dependency issue maybe related to pytest-asyncio if used.

**Review by wbarnha — CHANGES_REQUESTED** [review]
I've re-read this MR several times and I'm still baffled as to why this test is failing:
```python
 =================================== FAILURES ===================================
_____________ test_Service.test_wait_first__propagates_exceptions ______________

self = <t.unit.test_services.test_Service object at 0x7f2d2cd492d0>

    @pytest.mark.asyncio
    async def test_wait_first__propagates_exceptions(self, *, service):
        exc = KeyError("foo")
        m1 = Mock()
        m1.done.return_value = True
        m1.exception.return_value = exc
        m1.result.side_effect = exc
        with patch("asyncio.wait", AsyncMock()) as wait:
            wait.return_value = ((m1,), ())
            with pytest.raises(KeyError):
>               await service.wait_first(asyncio.sleep(5), timeout=5)

t/unit/test_services.py:629: 
```
I'll need to look around more.

**Comment by manawasp** [comment]
No pb !

I strongly believe fixing pytest-asyncio in test to `0.21.1` will fix the issue related to https://github.com/pytest-dev/pytest-asyncio/issues/706

**Review by wbarnha — APPROVED** [review]
`pytest-asyncio` is having some issues right now, so pinning is the right move for now. LGTM!

**Pull request merged**
