### PR TITLE
Ensure future in sleep method

### LINKED ISSUE #33: crash after upgrading Faust to v0.10.0 + Mode to v0.3.1
## Checklist

- [x] I have included information about relevant versions
- [ ] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

After I upgrade faust-streaming==0.10.0, it goes crash like this.

스크린샷 2022-11-30 오후 2 46 53

## Expected behavior

Tell us what you expected to happen.

## Actual behavior

Tell us what happened instead.

## Full traceback

```pytb
[2022-11-30 14:44:27,908] [6] [INFO] [^Worker]: Starting... 
[2022-11-30 14:44:27,912] [6] [INFO] [^-App]: Starting... 
[2022-11-30 14:44:27,913] [6] [INFO] [^--PrometheusMonitor]: Starting... 
[2022-11-30 14:44:27,913] [6] [INFO] [^--Producer]: Starting... 
[2022-11-30 14:44:27,913] [6] [INFO] [^---ProducerBuffer]: Starting... 
[2022-11-30 14:44:27,918] [6] [WARNING] Sending username and password in the clear 
[2022-11-30 14:44:27,919] [6] [INFO] Authenticated as user via PLAIN 
[2022-11-30 14:44:27,923] [6] [WARNING] Sending username and password in the clear 
[2022-11-30 14:44:27,924] [6] [INFO] Authenticated as user via PLAIN 
[2022-11-30 14:44:27,928] [6] [INFO] [^--ThreadedProducer]: Starting... 
[2022-11-30 14:44:27,930] [6] [ERROR] [^--ThreadedProducer]: Crashed reason=RuntimeError("Task <Task pending name='Task-12' coro=<Event.wait() running at /usr/lib/python3.8/asyncio/locks.py:309> cb=[_release_waiter(<Future pendi...fe590bbe0>()]>)() at /usr/lib/python3.8/asyncio/tasks.py:429]> got Future <Future pending> attached to a different loop") 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mode/services.py", line 843, in _execute_task
    await task
  File "/usr/local/lib/python3.8/dist-packages/mode/threads.py", line 182, in _keepalive2
    await self.sleep(1.1)
  File "/usr/local/lib/python3.8/dist-packages/mode/services.py", line 696, in sleep
    await asyncio.wait_for(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/usr/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
RuntimeError: Task <Task pending name='Task-12' coro=<Event.wait() running at /usr/lib/python3.8/asyncio/locks.py:309> cb=[_release_waiter(<Future pendi...fe590bbe0>()]>)() at /usr/lib/python3.8/asyncio/tasks.py:429]> got Future <Future pending> attached to a different loop
[2022-11-30 14:44:27,931] [6] [ERROR] [^Worker]: Error: RuntimeError("Task <Task pending name='Task-12' coro=<Event.wait() running at /usr/lib/python3.8/asyncio/locks.py:309> cb=[_release_waiter(<Future pendi...fe590bbe0>()]>)() at /usr/lib/python3.8/asyncio/tasks.py:429]> got Future <Future pending> attached to a different loop") 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mode/worker.py", line 279, in execute_from_commandline
    self.loop.run_until_complete(self._starting_fut)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/mode/services.py", line 800, in start
    await self._default_start()
  File "/usr/local/lib/python3.8/dist-packages/mode/services.py", line 807, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.8/dist-packages/mode/services.py", line 831, in _actually_start
    await child.maybe_start()
  File "/usr/local/lib/python3.8/dist-packages/mode/services.py", line 859, in maybe_start
    await self.start()
  File "/usr/local/lib/python3.8/dist-packages/mode/services.py", line 800, in start
    await self._default_start()
  File "/usr/local/lib/python3.8/dist-packages/mode/services.py", line 807, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.8/dist-packages/mode/services.py", line 831, in _actually_start
    await child.maybe_start()
  File "/usr/local/lib/python3.8/dist-packages/mode/threads.py", line 155, in maybe_start
    await self.start()
  File "/usr/local/lib/python3.8/dist-packages/mode/threads.py", line 176, in start
    await self._thread_running
  File "/usr/local/lib/python3.8/dist-packages/mode/services.py", line 843, in _execute_task
    await task
  File "/usr/local/lib/python3.8/dist-packages/mode/threads.py", line 182, in _keepalive2
    await self.sleep(1.1)
  File "/usr/local/lib/python3.8/dist-packages/mode/services.py", line 696, in sleep
    await asyncio.wait_for(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/usr/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
RuntimeError: Task <Task pending name='Task-12' coro=<Event.wait() running at /usr/lib/python3.8/asyncio/locks.py:309> cb=[_release_waiter(<Future pendi...fe590bbe0>()]>)() at /usr/lib/python3.8/asyncio/tasks.py:429]> got Future <Future pending> attached to a different loop

```

# Versions

* Python version: 3.8.10
* Faust version: faust-streaming==0.10.0
* Operating system: ubuntu 20.04
* Kafka version
* RocksDB version (if applicable)

### PR DESCRIPTION
**Pull request by wbarnha**
Hopefully this will fix #33.

### CODE REVIEW

**Comment by wbarnha** [comment]
Tests pass for Python 3.10 on my machine. I need to fix the GitHub runners...

**Comment by lqhuang** [comment]
LGTM. Otherwise, may I suggest to add an unitttest for similar function calls?

**Review by lqhuang — APPROVED** [review]

**Comment by lqhuang** [comment]
It's a little wired why no result of CI was reported now.

**Comment by wbarnha** [comment]
> LGTM. Besides, may I suggest to add an unitttest for similar function calls?

I agree, this is probably the right move. I've been lazy about adding unit tests when I claim to be fixing issues.

**Comment by lqhuang** [comment]
@wbarnha Could you check line 908 in the same file and update it like what you did yet.

**Comment by lqhuang** [comment]
> I agree, this is probably the right move. I've been lazy about adding unit tests when I claim to be fixing issues.

I know, LOL 😂 At least, let's merge this PR.

**Comment by lqhuang** [comment]
Did you already see reported CI results? In my side, none of CI jobs has started and the merge button is in disable status.

**Comment by wbarnha** [comment]
> Did you already see reported CI results? In my side, none of CI jobs has started and the merge button is in disable status.

Currently looking into it. We've had similar issues occur in the past with Faust, albeit rarely. It's similar to what's reported in https://github.com/orgs/community/discussions/26698.

**Comment by lqhuang** [comment]
Seems you forget to update [line 908](https://github.com/faust-streaming/mode/blob/2f126d0c5de7d42fc3543bd2391198b665bbea39/mode/services.py#L908)

```python
await asyncio.wait_for(
    self._shutdown.wait(),
    self.shutdown_timeout,
)
```

**Comment by wbarnha** [comment]
> > @wbarnha Could you check line 908 in the same file and update it like what you did yet.
> 
> Seems you forget to update [line 908](https://github.com/faust-streaming/mode/blob/2f126d0c5de7d42fc3543bd2391198b665bbea39/mode/services.py#L908)
> 
> ```python
> await asyncio.wait_for(
>     self._shutdown.wait(),
>     self.shutdown_timeout,
> )
> ```

Funny enough, I saw that exact section and when I tried changing things, the unit tests failed. I'll need to take another look at it.

**Pull request merged**
